apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-addons
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - matrix:
        generators:
          - git:
              repoURL: https://github.com/ffelipek07/argocd-test.git
              revision: feat/devops
              directories:
              - path: applicationset/apps/*/helm
          - git: 
              repoURL: https://github.com/ffelipek07/argocd-test.git
              revision: feat/devops
              pathParamPrefix: cfg
              files:
                - path: applicationset/configs/dev.json
  template:
    metadata:
      name: '{{index .path.segments 2}}-{{.cluster.nome}}'
    spec:
      project: "default"
      source:
        repoURL: https://github.com/ffelipek07/argocd-test.git
        targetRevision: feat/devops
        path: '{{.path.path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{index .path.segments 2}}'
      syncPolicy:
        automated: {}
        syncOptions:
        - CreateNamespace=true